### ISSUE TITLE
Question: Support for Emby?

### ISSUE THREAD

**Issue by EffeF** [Tautulli/Tautulli#1120]
Today Emby is an established alternative to Plex, a very good alternative, and it is increasingly popular (especially after the polemics on privacy).

I know that making a version for Emby would be a big job, but is there a chance that this will happens?

Things have changed since it was last asked: #379

**Comment by JonnyWong16** [comment]
No.

**Comment by Arcanemagus** [comment]
> Things have changed since it was last asked

I'm rather curious what you think has changed since that issue? This would still require almost an entire rewrite of the server communication.

**Comment by EffeF** [comment]
> I'm rather curious what you think has changed since that issue?

The spread of Emby. Compared to two years ago, many more people use Emby (many at the expense of Plex). The number of users is a good justification for necesarry work, I think.

**Comment by Arcanemagus** [comment]
> The number of users is a good justification for necesarry work, I think.

You're perfectly free to fork this and do the work yourself 😛.

**Comment by EffeF** [comment]
I do not know Python, I would have done it very willingly.

I just wonder if Emby was at least considered seriously...

**Comment by filoor** [comment]
Would be nice to add Emby :D

**Comment by Hellowlol** [comment]
I would like a pink unicorn pls. :D This request would require a entire rewrite of plexpy. Almost everything is plex specific.

**Comment by EffeF** [comment]
> Would be nice to add Emby :D

Yes, it would be nice, but judging by the clear rejection they are not even going to take it into consideration.

I switched to Emby a year ago, and Plexpy's statistics are the only thing missing. Fortunately other third-party tools born with Plex which I used have added support to Emby, and notifications are integrated into Emby... statistics only are missing.

> This request would require a entire rewrite of plexpy.

Can Emby API are not they useful? Really an **entire** rewrite?
Emby is a consolidated alternative to Plex. I just ask that this is taken into account.

**Comment by Arcanemagus** [comment]
> Can Emby API are not they useful?

The usefulness of any Emby API isn't the main problem, it's that the code in PlexPy is written specifically for working with _Plex_. To get it to work with Emby also you would need to:

1. Create an internal interface that abstracts out everything specific to the server it is talking to. Note that this would need to be flexible enough to handle the unique characteristics of Plex _and_ Emby and ____.
2. Rewrite most of PlexPy to use this new interface instead of the Plex specific code. Includes creating an adapter for Plex for this internal interface.
3. Create an adapter to plug Emby into this internal interface.

That's an extremely simplified overview, as @Hellowlol and I have both said this amounts to essentially rewriting all of PlexPy that isn't user facing, and a lot of the parts that are. Since everyone that actually works on PlexPy is using Plex, and nobody that uses Emby seems willing to take on the massive work required, nothing will happen.

**Comment by JonnyWong16** [comment]
* Find: `Plex`
* Replace with: `Emby`

**Comment by EffeF** [comment]
> everyone that actually works on PlexPy is using Plex, and nobody that uses Emby seems willing to take on the massive work required

Thanks @Arcanemagus, finally a serious answer... much better than a simple "no" or other sarcastic answers.
