### ISSUE TITLE
Reinstalled OS and PMS, removed dupe libraries, and now history is gone.  Can that be fixed?

### ISSUE THREAD

**Issue by flyize** [Tautulli/Tautulli#1261]
**Version:**
1.4.25

**Branch:**
Master

**Hash:**
cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

**OS:**
Windows

**Python Version:**
Python 2.7

As stated in title, I recently reinstalled my server OS and PMS.  When I restored PlexPy from backup, there were of course duplicate libraries.  After updating my PMS token, I was able to remove the duplicates.  I assume my history was tied to the dupes, which are now gone.  Is it possible to preserve that history somehow (I still have the backups of course)?

**Comment by Arcanemagus** [comment]
You'll need to use something like [update_all_metadata.py](https://gist.github.com/JonnyWong16/f554f407832076919dc6864a78432db2) to update your history entries to the new locations. Note that you should only run this _after_ the new libraries have gathered their metadata as this preforms title matches between content.

Since this isn't a bug, this issue should be closed, if you need further help please use one of the [support options](http://tautulli.com/#support).

**Comment by flyize** [comment]
Can you explain that process?  I assume this means that I need to restore the old database and then run it?  And how do I know when PlexPy has all the proper metadata for the 'new' libraries?
