### ISSUE TITLE
Set Name / Label for Notification Agents

### ISSUE THREAD

**Issue by Ltek** [Tautulli/Tautulli#1396]
**Is your feature request related to a problem? Please describe.**
we cannot change the name from the defaults like MQTT (8) ... this makes it impossible to know what the agent is/does without opening each one

**Describe the solution you'd like**
Allow us to rename them

**Describe alternatives you've considered**
there are none

**Additional context**
this should be simple, yes?

**Comment by JonnyWong16** [comment]
There is a description field at the bottom of every notification agent configuration tab.

**Comment by Ltek** [comment]
> There is a description field at the bottom of every notification agent configuration tab.

I didnt know -- that field is not intuitive; and the 'description' is small & difficult to read. 
Would we far better to rename the Notification title/label to something that makes sense

**Comment by JonnyWong16** [comment]
I honestly don't understand what you mean.

If you enter a the description 
```
Turn off living room lights when movie starts
```
![image](https://user-images.githubusercontent.com/9099342/111888139-1298c180-8997-11eb-80e3-a31cad69f79d.png)

Then the notification agents list will show
```
MQTT (8 - Turn off living room lights when movie starts)
```
![image](https://user-images.githubusercontent.com/9099342/111888141-19bfcf80-8997-11eb-9d2d-561e56bf80fc.png)

Is that not what you are asking for? To add a label (description) so you can tell what the notification agent does without opening the settings. Because I don't understand what you are asking for. Do you want to get rid of the "MQTT" part?

**Comment by Ltek** [comment]
@JonnyWong16   replace MQTT (and the not helpful number attached) so the largest text is whatever we want - and the smaller text is the description.  "MQTT" is the not needed information yet the largest and easiest to read where the description is difficult to read, barely visible. The number is irrelevant and provides no usefulness for identification. 

For instance, in repo no one names code or container image "C++" -- cuz the coding language is not the most important way to find what you are looking for. They name it somethings useful like "app_name-gateway" or "app_name-plugin", etc

Its helpful for us to have labels/names we can control, with description if needed. Like...

MediaRoom (data for Homeseer events)
or
Playroom (send alert to parents when turned on)
or
Livingroom (general notifications)

**Comment by JonnyWong16** [comment]
I disagree. The type of agent is important when you have a lot of different types of notification agents.

For example, I use multiple Discord, Email, Scripts, and Webhooks. When I go to the notification agent list I need to know which agent is Discord for recently added vs Webhook for recently added vs Email for recently added. I look for the type of agent first - Discord or Webhook or Email. The number is the ID used for interacting with the API so I need to know the ID at a glance without opening the settings.

For majority of users, having the agent type listed makes a lot more sense because that is what they added. They didn't add a living room agent, they added a Discord agent. Asking the user to manually add the agent name to the description is unintuitive. 

Also since the description is optional, there needs to be a default way of displaying and separating agents in the list which is done by the agent name and a unique ID number that will never conflict. Removing the ID number will cause someone to have a list of "Discord" without any way of separating them if none of them have description.

Furthermore, having two different list styles for agents without a description and agents with a description is unacceptable. The list style must be uniform.

Example, this is _unacceptable_ because the same data (agent name) is positioned in different locations:
```
Discord (3)  <-- agent without a description
Living Room (Discord)  <-- agent with a description
```

**Comment by Ltek** [comment]
Please, at least make the Description text blue or white or deep red or something to provide contrast against the black and make it easier to read. 

btw, it sounds like this may be a matter of how you code, and thus mainly care about the transport method. When people use the agent to automate something, they care about the automation. Not the method.... thus a unique label for quick identification of what I want to look at or edit, or add a new function is important, far more than 'how' its occurring (email, mqtt, etc).  Generally, the end result matters more than the how. 

For instance, say I have 10 or 20 MQTTs... I may need to read (nearly) every line's description (which is hard due to the text color and small size) to find what I want. But if only 2 of those labels were instead, "Media Room" my eye can catch that immediately and quickly and now I only need to read 2 lines.

**Comment by JonnyWong16** [comment]
You can change the size/colour yourself by using something like [Stylus](https://add0n.com/stylus.html) or [sub filter through a reverse proxy](https://github.com/gilbN/theme.park).

Red and blue do not fit the theme of the rest of the application.

**Comment by JonnyWong16** [comment]
One thing I will consider is changing the entire list to a table layout instead.

> btw, it sounds like this may be a matter of how you code, and thus mainly care about the transport method. 

My way of doing this is equally valid to your way of doing things. Whatever solution comes out of this needs to be able to satisfy both. I need to be able to see the information I want, and you want to be able to see the information you want.

**Comment by Ltek** [comment]
> One thing I will consider is changing the entire list to a table layout instead.
> 
> > btw, it sounds like this may be a matter of how you code, and thus mainly care about the transport method.
> 
> My way of doing this is equally valid to your way of doing things. Whatever solution comes out of this needs to be able to satisfy both. I need to be able to see the information I want, and you want to be able to see the information you want.

I agree... your use case was not one I had thought about prior. Equally valid, of course.

Thank you for talking it through with me.
