### ISSUE TITLE
Single episode notification sent as a show notification

### ISSUE THREAD

**Issue by 2SweetMusicNerd** [Tautulli/Tautulli#1420]
**Describe the Bug**
Notifications on discord for recently added say season 0 whenever I add a new show whether it be one ep or a full show adding to an exiting show works fine it says the right stuff

**Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior**

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. <show> {show_name} Season {season_num}</show><season>{show_name} - Season {season_num} Episodes {episode_num}</season><episode> {show_name} - Season {season_num} Episode {episode_num} - "{episode_name}"</episode><movie>{title} ({year})</movie> :point_left: was just added to Plex!
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version:V2.7.0 
- Git Branch: master
- Git Commit Hash:c780f1fd6c57763bd0e39253ffc55be2618050ea
- Platform and Version: Windows 10
- Python Version: 3.8.8
- Browser and Version: Version 90.0.4430.85 (Official Build) (64-bit)

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).
https://gist.github.com/2SweetMusicNerd/4a09530f8a554ff8f703fc8ca12189e9

**Comment by enchained** [comment]
@2SweetMusicNerd could you please add your Plex Server version to the bug description?

I have a similar issue with the latest Plex version.

Plex Media Server version: 1.22.2.4282-a97b03fad
Tautulli version: v2.7.0
Git Branch: master
Git Commit Hash: v2.7.0
Platform and Version: [Docker] Linux 3.10.105 (#25426 SMP Mon Dec 14 18:45:24 CST 2020)
Python Version: 3.8.8
Browser and Version: Version 90.0.4430.85 (Official Build) (64-bit)

If you add a single episode of a completely new show, you will get a notification with the media type "show" (which usually results in Season 0 notification, depending on the template). This happens even if you disable any notification grouping.

I have no experience with debugging python, but possibly `on_created(rating_key)` is getting called instead of `on_created(grandchild_key)`. That could happen if for some reason `child_keys = RECENTLY_ADDED_QUEUE[rating_key]` turns empty, but I don't know how `RECENTLY_ADDED_QUEUE` is formed.

I added pilot episodes to beta and legacy(regular) TV libraries (see the events after `2021-04-19 17:58`). Section 26 library (with Deadly Class) is beta, section 27 (with The Umbrella Academy) isn't. Both having the same issue for me.

Logs: https://gist.github.com/enchained/374672106e5160f314bdb07be624b2d4

**Comment by 2SweetMusicNerd** [comment]
Version 1.22.2.4282

**Comment by 2SweetMusicNerd** [comment]
@enchained Version 1.22.2.4282
Im new to this I don't know what I'm doing
