### ISSUE TITLE
Enhancement Request - Allow for # seconds/minutes between duplicative watch notifications 

### ISSUE THREAD

**Issue by twicehopped** [Tautulli/Tautulli#1439]
**Is your feature request related to a problem? Please describe.**
Yes - Unfortunately it seems when one of my users is watching a show, if they add subtitles Plex considers this a brand new watch. Same for if they change resolution.

This can result in multiple Playback Start notifications being sent within 1 minute (especially annoying if they change resolution and then add subs, resulting in 3 notifications).

**Describe the solution you'd like**
With the recent update for suppressing duplicative notifications for server down, etc., can that be extended to other types of notifications such as Playback Start?  Maybe give a field for number of minutes between sending the exact same notification?

**Describe alternatives you've considered**
I'm not aware of any alternative solutions.

**Additional context**

**Comment by twicehopped** [comment]
Sorry - I think I completed the template? Let me know if any additional info is needed, thanks!

**Comment by JonnyWong16** [comment]
That sounds like a Plex client issue/bug. Changing subtitles or quality during playback _does not_ start a new session. *Go test this yourself.* If this is a Plex bug then you should report it to Plex to get it fixed.

The only way that would happen is if they are stopping the stream to toggle subtitles on the preplay page. In that case, both Plex and Tautulli are correct and it _is_ starting a new session. I'm not inclined to make any changes since this would be correct and expected behaviour. They stopped and started -> new session -> new notification.

If you don't like either of those options, then I would suggest running your own notification script to do your own filtering.

**Comment by JonnyWong16** [comment]
I just remembered that Tautulli already has this feature. It's called the "Continued Session Threshold" (Settings > Notifications & Newsletters > Show Advanced).

![image](https://user-images.githubusercontent.com/9099342/119531591-f0297880-bd38-11eb-97c5-22a156752122.png)

Then you add a condition of `Initial Stream | is | 1` to your notification agent.

![image](https://user-images.githubusercontent.com/9099342/119531460-c96b4200-bd38-11eb-9bbb-fd76c02480b5.png)

This feature was meant to be used with continuous music playback so you only get one notification for the first track you play, but it will also work for your situation.

**Comment by twicehopped** [comment]
Just tested it out - it works great! Thank you so much, really appreciate this quick responses here.

Thanks for a great product, I think we can close this issue as resolved.
