### ISSUE TITLE
[Feature Request] Selective ignoring of items

### ISSUE THREAD

**Issue by JonnyWong16** [Tautulli/Tautulli#216]
Add the ability to select certain items which would be ignored from logging.

Examples:
- To prevent custom pre-roll videos from being logged.
- To stop logging all the times your daughter is watching _Frozen_.
- To hide your own watch history of _My Little Pony_.

(I've started a bit on this feature.)

**Comment by mmenanno** [comment]
I was told to add my idea here, of ignoring entire libraries from logging. 

Example being if you have libraries for Movies, TV Shows, Anime, and HomeMovies, being able to tell it to never log anything from HomeMovies

**Comment by Hamst3r** [comment]
Another vote for this sort of feature.

**Comment by phunkysai** [comment]
I would also like this....if possible, I think it should still log the viewing of the file, but we should be able to select shows or movies or whatever that don't show up in the reports. 

That way I can exclude _Friends _for showing as the most watched TV show since my wife falls asleep to it and it plays continuous episodes for hours on end! :-P
