### ISSUE TITLE
Season/episode tag is not shown correctly in notification

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#299]
When i get a push message on an added TV show episode, i get the following. The season/episode tag is not shown correctly.

Message body:
{title} <movie>({year})</movie><tv>(S{season_num}E{episode_num})</tv> is added to {server_name} in section {media_type}. <movie>Summary: {summary}</movie>

Message is received:
Ultimate Airport Dubai (SE1) is...

fyi. Notification Delay is set to 60 seconds

**Comment by roelbeun** [comment]
When using the tag {season_num00} and {episode_num00} i get: S00E01

**Comment by JonnyWong16** [comment]
So it should be S0E1? The 0 is missing?

**Comment by roelbeun** [comment]
No S03E06

**Comment by JonnyWong16** [comment]
Is it correct in Plex?

**Comment by roelbeun** [comment]
Yes

**Comment by JonnyWong16** [comment]
It could be possible that metadata didn't finish processing before the notification was sent. You can try increasing the delay.

**Comment by zobe123** [comment]
Same here...
![image](https://cloud.githubusercontent.com/assets/13840542/11407858/c914e8e0-93b5-11e5-8094-982685199fb2.jpeg)

**Comment by JonnyWong16** [comment]
Try increasing the delay.

**Comment by zobe123** [comment]
I'm sorry, increasing the delay doesn't work.
All the other metadata are working correctly.
I try this <tv>(S{season_num}E{episode_num})</tv> With 60, 90 and 120sec delay

**Comment by JonnyWong16** [comment]
Will look into this when I get home.

Thought crossed my mind. Do you guys have the option "Group notifications for recently added TV Shows or Music" checked?

If it's sending a notification at the TV Show level, then it won't provide any season or episode number.

**Comment by zobe123** [comment]
Thanks a lot, man!

I have deactivated "Group notifications for recently added TV Shows or Music" and then i get the correct numbers (without any 0) - i hope this is helpful

**Comment by roelbeun** [comment]
When i check-OFF the option "Group notifications for recently added TV Shows or Music", i do get the correct S--E-- tag's. Bug or as designed?

**Comment by JonnyWong16** [comment]
Checked grouped = Notification at the **TV Show** level. There **are no** S#E# for a show.
Unchecked grouped = Notification at the **Episode** level. There **are** S#E# for an episode.

**Comment by roelbeun** [comment]
Notification exclusion tag possible? <tv-not-grouped></tv-not-grouped>

**Comment by JonnyWong16** [comment]
Not sure what you mean.

**Comment by roelbeun** [comment]
With those tags it would be possible to do:  <tv-not-grouped>S{season_num00}E{episode_num00}</tv-not-grouped>.

Then only when a non-grouped alert is being send, it will hold the S/E tag.

**Comment by JonnyWong16** [comment]
I don't see the point in this.

It will either send grouped notifications, or un-grouped notifications, not both.

**Comment by khag7** [comment]
I'd really like to use S{season_num00}E{episode_num00} when the batch only contains one episode and also have grouped notifications if the batch contains more than one episode. I'd suggest implementing some code which checks to see if the batch contains only one item and if so to classify the media type as single. Then add a notification exclusion tag <single> so that I can make my notification text look like this:
`{title}<tv><single> S{season_num00}E{episode_num00}</single></tv> was added to Plex`

The result is that the notification can handle proper display for a single episode download, multiple episode downloads at once, or a movie download. It incorporates the title, and if it's a tv show with only a single episode it will include the season and episode numbers.

**Comment by carlosrovira** [comment]
>  I'd suggest implementing some code which checks to see if the batch contains only one item and if so to classify the media type as single

I think as well something should be done since when an album or a season is added multiple notifications are sent flooding the user. For example if all episodes from a TV show are added there should be only one notification. Or if half of the episodes are added, there should be one notification, and then when you add the other half, another notification. Make this sense?

Thanks!
