### ISSUE TITLE
Alert on simultaneously plays

### ISSUE THREAD

**Issue by roelbeun** [Tautulli/Tautulli#305]
Looking for an option to identify accounts which are shared among other homes. I think of doing this based on the ip address. When a user is watching "recently" from two different ip address, throw a message. Or when a simultane watch is going on from one user account.

Throwing a message primarly in the user profile in PlexPy, maybe extend this to notification alert.

Any ideas about this?

**Comment by Hellowlol** [comment]
Why would any be interested in this? Are there people out there renting out there server or something?

**Comment by Arcanemagus** [comment]
This _really_ sounds like somebody renting out their server, which is explicitly against the [Plex Terms](https://plex.tv/legal)...

**Comment by roelbeun** [comment]
No, family is also watching. I want to avoid an overload of users on a single account. I want to know when people are using multiple devices at the same time. So different ip addresses are not that interesting. 

Money for Plex is something I would never do. So let's make that clear.

**Comment by Arcanemagus** [comment]
Unlike other streaming services you may have used there is no limit on the number of simultaneous access to an account. Similarly there is no limit on the number of accounts that a Plex server can be shared to. The only limit is in how many simultaneous streams your server has the capability to send / transcode media for.

**Comment by roelbeun** [comment]
Well, I guess I just want to know it then :) maybe an developer can look into this if it's possible to implement. Plexpy feels like the place to implement this kind of information.

**Comment by JonnyWong16** [comment]
If you get two start notifications before a stop notification from the same user then they are simultaneously streaming from two places?

**Comment by drzoidberg33** [comment]
I'll add this as an enhancement request but not really sure how popular this one will be, we've already got a metric butt tonne of notification triggers.

You can manually audit accounts you think may be sharing accounts by looking at the start/stop times on their respective histories.

**Comment by roelbeun** [comment]
I agree. Thanks.

**Comment by zobe123** [comment]
my thoughts: if this Feature would be implemented it could get plexpy into Trouble, maybe... i don't think so.
on the other side then plexpy would be the first Feature/App/Docker/etc whos able to notify when someone share his account to a third Person (paid or not...to judge that should not be the task of this program) it would only notify, not preventing from it - i think this could get an killer-feature for the community ;-)

**Comment by roelbeun** [comment]
Nobody is talking about money in the first place. I want to know if there are simultaneously plays from the same account. That's it. Keep assuming...  The request has been torn out of control.

**Comment by JonnyWong16** [comment]
This can be done with a custom script now.

**Comment by BeeVee2015** [comment]
Actually like this idea as well...shared my server with family/friends and having the issue of people sharing their usernames and logins all over the place. It's more a matter of a trust issue and since I'm not hosting a server that can handle heavy bandwidth, wanted to use something like this to weed out the people who are doing so. Any help would be appreciated. Thanks!

**Comment by Hellowlol** [comment]
You can use new api to get current streams (cmd=get_activity) and just process any dupes from there. You kill any streams if there multiple users at the same time so the bastards learn (see the wiki for example)

**Comment by BeeVee2015** [comment]
Sweet. So there's a way to kill individual streams but since I'm rarely ever at the server when it's happening, I was looking for a way to be notified that a user is streaming different content from different IPs at the same time... or multiple IP logins within 2-3 hours or each other. Thanks for the heads up though, sorry if this question was already asked. Going to browse the wiki now.

**Comment by Hellowlol** [comment]
I was bored at work so i started on a script for you, it isnt finished since i dont remember the format the session are, you need to handle that parsing your self. It could be a nice starting point at least. The script is untested as i dont have access to python at work. https://gist.github.com/Hellowlol/85dd6b4a6ae8f177c590

**Comment by BeeVee2015** [comment]
Thanks! Been so busy at work lately but will try to give a go on the weekend! Appreciate your help.
