### ISSUE TITLE
[Feature Request] Data transfer statistics

### ISSUE THREAD

**Issue by scrap3r** [Tautulli/Tautulli#430]
Is it possible to get some sort of data transfer statistics based on file sizes/plays?

**Comment by pax0707** [comment]
And if possible WAN / LAN.

**Comment by drzoidberg33** [comment]
It's been requested many times before but it's not currently possible to get a reliable bandwidth value.

**Comment by scrap3r** [comment]
Bummer, thanks for the quick reply.

**Comment by wnielson** [comment]
Sorry to resurrect a closed issue, but I independently started working on adding this feature and just noticed that it has been requested a few times.  So, I thought I would share what I've done so far regarding bandwidth monitoring.  The tl;dr here is that I believe it is possible (and not too difficult) to add this feature in a cross-platform manner.

I've implemented a simple packet monitor using the pcap library and the Python bindings.  This can easily be made cross-platform using either libpcap (*nix) or WinPcap (Windows).  I tested the performance of the Python packet monitor while saturating a 100Mbit connection and the CPU utilization remains low (less than 15% of a single core).  I've integrated the packet monitor into PlexPy like so: when a new stream is started (and the client's IP address is known), PlexPy tells the packet monitor to collect data on the outbound traffic to that IP address.  The bandwidth (bytes per second) is then recorded every second and logged.  When the client stops playing an item, the filter is removed from the packet monitor.

Currently, there are two main issues that I can think of.  The first is that it appears quite a few people use PlexPy on a different machine than `PMS` is installed on.  The implementation I've done so far will not work in this type of setup because it requires the packet monitor, PlexPy and `PMS` to reside on the same machine.  This can be very easily solved by moving the packet monitor into a standalone application that provides a REST interface that PlexPy can communicate with.

The second issue is the trickier of the two and arises when multiple streams are going to the same IP address.  The solution to this problem lies in tracking client IP addresses **and** port numbers.  Unfortunately the port number is not reported in the `/status/sessions` endpoint, but it is displayed in the `PMS` log file.  For example:

```
Feb 22, 2016 16:58:51 [0x7fd1e5bfe700] DEBUG - Completed: [11.22.33.44:54189] GET /library/parts/52539/file.mp4 (7 live) TLS 957722ms 165895830 bytes 200
```

Where in this example `11.22.33.44` is the IP address and `54189` is the port number.  The packet monitor can then simply keep track of the bandwidth to a specific IP address and port.

**Comment by Hellowlol** [comment]
If I needed this info I would use a docker or vm with vnstat installed.

**Comment by wnielson** [comment]
@Hellowlol 
That would get you general bandwidth info, but you wouldn't be able to determine the bandwidth used per stream.

**Comment by Hellowlol** [comment]
True, but the op didn't mentioned anything regarding per stream so I just assumed it would be in general. Why would data used per stream be interesting anyway? I just assumed people would "need" this because of data caps

**Comment by wnielson** [comment]
I can think of a couple of reasons that per-stream data could be useful.  First, you could see stats on bandwidth consumption per user.  You could also use this data to view your network performance to see how your available bandwidth is keeping up (or not) with demand.  I'm sure other people have use cases as well, hence the reason this has been requested multiple times (#155, #270).

Plus, Plex is a media streaming application and it would be nice to have data on the actual streams.
