### ISSUE TITLE
Feature: Retain statistics with move

### ISSUE THREAD

**Issue by neebski** [Tautulli/Tautulli#458]
I have a "New Content" library on my Plex server that is populated with auto downloads and such, PlexPy works fine with tracking the plays from this but my question is can PlexPy retain the watch count and statistics generated when I move a movie from this new content folder to my main movies folder.

Not a huge deal just something I noticed.
Love PlexPy though! Great information :)

**Comment by JonnyWong16** [comment]
Yes, but with a bit of work.

The links will be broken (because the ID changes in Plex when you move something), but you can fix them manually by clicking on the item in your history, then clicking "Fix Metadata". PlexPy will prompt you to pick the matching item and it will update the IDs in the database.

If you have a lot of history items, this could take a while to fix one by one. I have plans to add a mass update feature, but that's way off in the future.

You don't have to fix the links. Everything should still work, but the the play counts for that item would start from zero again in the new library.

**Comment by neebski** [comment]
Well that's fantastic to hear. I just ran to my PlexPy to try and find the "Fix Metadata" button/link/icon/blurb but do not see anything in the history.

Am I missing anything?

**Comment by JonnyWong16** [comment]
Sorry, it's currently on the dev branch. I'm still improving it.

**Comment by neebski** [comment]
Well, I could always just continue as is then maybe in the future I can do a mass update as you mentioned. Thanks for your quick reply!

**Comment by Hellowlol** [comment]
Could we use guessit and fuzzywuzzy to compare the two filenames and prompt the user if there are less then x procent confidence.

**Comment by JonnyWong16** [comment]
We can actually compare the IMDB ID or TVDB ID for an exact match (only if they use those agents though).

**Comment by Hellowlol** [comment]
that would be even better, if could fall back to guessit/fuzzywuzzy if they don't. I don't believe anybody would disable them... Are those ids listed in plexpy db atm?

**Comment by JonnyWong16** [comment]
Yep, it's listed under the `guid` column.

**Comment by Hellowlol** [comment]
I assume you got this covered then ;)

**Comment by neebski** [comment]
Bravo to the new update. I applaud you!! Now my question is this, now that we have "fix metadata" in master branch does fixing this work across libraries or is that still a work in progress?

Thanks!

**Comment by JonnyWong16** [comment]
It will work across libraries, but still only one item at a time.
