### ISSUE TITLE
Recently added bug (or not?)

### ISSUE THREAD

**Issue by MrFisher1990** [Tautulli/Tautulli#459]
For 2 times in a row now (luckily not more then that)

I receive notifications of materials added to plex. Not 1 no my complete library gets re-added.

Which means I get 400+ notifications when that happens. While nothing of my content has been changed, replaced to another location or added.

Is this a know issue?

MrFisher1990

**Comment by JonnyWong16** [comment]
I have not seen this before. 

Maybe it's your Plex server? What are you update/refresh library options set to?

**Comment by MrFisher1990** [comment]
Update interval 15 minutes

Plex version: Version 0.9.15.1 

It happened two times (with 2,5 weeks between the events). The first one was around 16:15 but the last time it was in the middle of the night (and I am not the only one receiving the notifications). Their phones literally froze. Haha

**Comment by Hellowlol** [comment]
Logs?

**Comment by mbnn** [comment]
Since the latest version (beta) of plexpy recently added doesnt work here anymore (ubuntu), when i press test to pushover/twitter it works fine but no new episodes get it :( Nothing specific in the logs.

I think this is related to: " PlexPy is updating library IDs in the database. This could take a few minutes depending on the size of your database. 
You may leave this page and come back later."

It has been saying that for 24 hours now. Same after a restart.

**Comment by JonnyWong16** [comment]
@mbnn Yes, monitoring is disabled while it is updating the database. It sounds like the database update crashed. How many lines of history do you have in PlexPy?

Try shutting down PlexPy, then set `update_section_ids = 1` in the `config.ini` file, and restart PlexPy. That should force it to try the update again.

**Comment by mbnn** [comment]
Did that, now I get (when restarting the process): "service plexpy restart
Job for plexpy.service failed because a timeout was exceeded. See "systemctl status plexpy.service" and "journalctl -xe" for details"

Update: retried it a few times not it seems to be back up :) Thank you. Once this is ok, should i put that update section ids back to -1?

**Comment by JonnyWong16** [comment]
No, It's automatic.

**Comment by JonnyWong16** [comment]
I think this is an issue with the Plex Server, not PlexPy. Reopen if the problem occurs again.
