### ISSUE TITLE
The library does not list multiple files

### ISSUE THREAD

**Issue by Hellowlol** [Tautulli/Tautulli#480]
Say you have a movies of 16 blocks, one in sd and one in hd it will only list one of them.

I think its caused by this line https://github.com/drzoidberg33/plexpy/blob/dev/plexpy/pmsconnect.py#L787

**Comment by royalef** [comment]
I wonder if this is the same root cause of what I'm seeing.  When there are multiple versions of a file, Plex choosing the higher/highest quality possible version, in my case I'm watching a 4K version.  On Plex client it shows the correct 4K stats and plays the 4K version.  But on PlexPy is says the 720p version was played.
