### ISSUE TITLE
[REQUEST] Sync status

### ISSUE THREAD

**Issue by kasper79** [Tautulli/Tautulli#52]
Would it be possible to add the sync status of the item currently being synced? Right now, all I can do is look at my process manager and see that "Plex New Transcoder.exe" is running.

Also, can you add to the "Synced Items" menu a "date synced" organization option?

Thanks!

**Comment by drzoidberg33** [comment]
I do want to improve the sync screen but you can already see pending syncs in the sync lists.

If a sync is busy it will have the status "Pending" in the "State" column and you will see the converted items will be less than the total items. Not a complete picture but it does give you the info you're asking for.

Regarding the date, that's a bit trickier. I would have put that in already if this information existed but the Plex api does not provide this (at least not when I did the implementation of the sync list). This would require me to build something that monitors the sync list periodically and build my own timestamps, it wouldn't give totally accurate data though which is why I never implemented this.

**Comment by kasper79** [comment]
Understood! Thanks for looking into it..  

On a side note to this, the iOS app (I haven't checked the new version yet) has a meter/percentage graph that tells the speed of the current transcode and sync session. Would that be able to be added?  I'd love to know what is currently being transcoded in the back ground :/

Thanks again!

PS. Donation sent! Loving this project!

Ryan

**Comment by JonnyWong16** [comment]
Could the sync time be determined from reading the time stamps in the PMS log file?

**Comment by drzoidberg33** [comment]
@JonnyWong16 Probably possible but it would mean PlexPy would constantly have to be checking the logs which is really not ideal. I don't really want to add any other features that rely on log trawling and would prefer to get rid of having to do so completely.
