### ISSUE TITLE
[Bug] Use Actual Artist rather than Album Artist

### ISSUE THREAD

**Issue by NedtheNerd** [Tautulli/Tautulli#600]
As the title says for Music.

**Comment by JonnyWong16** [comment]
Note to self: Track artist listed under `originalTitle` attribute in metadata XML.

**Comment by fcastilloec** [comment]
I actually prefer to track my artist as Album Artist. I have all my collection neatly organized by Album Artist. Many times there are many artist collaborating on one song, and the Artist field becomes irrelevant having all this names. Album Artist has always just one name and is the preferred way of organizing music.
Since not everybody will agree, having the option to track either Artist(s) or the Album Artist will be the best approach. Let the user decide.

**Comment by jrh3k5** [comment]
+1 for tracking by contributing artist, not album artist. I've got albums with multiple contributors categorized under an album artist of "Various Artists" - as a result, the "Various Artist" dominates the number of plays in my Plex stats.

**Comment by jlbarr** [comment]
I also would like to see something other than 'Various Artists' in my stats.

**Comment by Monstar316** [comment]
Various Artists is a bit vague. Better to have it under track artist rather than album artist.

**Comment by guyspr** [comment]
Maybe give us the option? "If album artist is VA/Various Artist, use Track Artist". I think that would give you the best of both worlds, because I agree with @fcastilloec as I have a few albums from one person, with some tracks featuring other artists. Those shouldn't go in the tracking, but various artists just doesnt make any sense.

Maybe even an option to set the artist filter, so you could add Various Artists, VA, V/A. To catch all options if your library isn't that greatly tagged ;)

**Comment by fcastilloec** [comment]
@guyspr best idea ever!
People don't want to track by Album Artist because of the "Various Artists", and can be a nightmare for everybody. My music is organized in a way that no track contains various artists. If a song comes from a compilation album, I simply put the album artist the same as the track artist, but not everybody likes that.
Being able to simply put an if statement for various artist will make everybody happy, unless somebody is actually wanting to track "Various Artists" itself, but I can't think of anybody that will do that.

**Comment by monstar316** [comment]
Any update on this one? Would be good to have it as @guyspr said.
