### ISSUE TITLE
Play duration and pause time mixed up.

### ISSUE THREAD

**Issue by MartinHaimberger** [Tautulli/Tautulli#669]
Git Branch: master
Git Commit Hash:    786a3742332bd9d1266b1c3d01e1432aea4f4143
Platform:   Windows 7
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]

Hi,

it seems that the play duration and the pause time are mixed up.

Nice Regards,
Martin

Log: http://pastebin.com/GVkc7Uvs
![2016-04-16 02_44_17-plexpy](https://cloud.githubusercontent.com/assets/4179112/14578022/7cdd040c-037d-11e6-81a1-38eda1cff86e.png)

**Comment by JonnyWong16** [comment]
I don't see anything wrong.

**Comment by MartinHaimberger** [comment]
@JonnyWong16 the thing wrong is here that the duration of the american dad episode is listed as 73 minutes and paused as 4 minutes, but it was the other way around (btw an american dead episode not 73 mins long)....

Can u see now ?

**Comment by Hellowlol** [comment]
So it was a 4 minute episode paused for 73 minutes? :P

**Comment by MartinHaimberger** [comment]
It played 4 minutes and was paused for 73 mintues. Right. So i think there is somehing mixed up ....

**Comment by Hellowlol** [comment]
It could be correct tho :P

**Comment by MartinHaimberger** [comment]
So then are most of the other items mixed up if this is correct. Other items show as duration the duration of the play. And in the pause it showes the paused time. 

However i m some times having items where it mixed up. So the duration is the pause time and the pause time is the duration, like the example i posted.

This messes up my statistics ....

**Comment by drzoidberg33** [comment]
Is it possible that PlexPy is being shut down and restarted during this time?

This would explain the long play time as if there is something playing when PlexPy is shutdown, when you start it up again and the episode ended while PlexPy wasn't running it will mark the end time as the time you started PlexPy again.

**Comment by MartinHaimberger** [comment]
I did not restart it per hand and if the services had gone done also the connection to the plex service should have been ended. But i cannot say i a hundret percent. I will have a look if plexpy was restarted ( in the logs), otherwise i will continue watching when this happens.

**Comment by Nyghto** [comment]
This issue is still here, I am seeing this problem with a specific platform only, Rasplex. It happens sometimes a pause gets registered as playing. Result: Getting play times over 2000 minutes if someone leaves it on pause for 1 day. Quite annoying because if this issue the 'total duration' time gets corrupted. I need to purge these stats from time to time to keep stats clean and real. 
![pause-as-play](https://cloud.githubusercontent.com/assets/1236301/25352989/10e82290-292e-11e7-998b-036dfc80a999.jpg)

**Comment by JonnyWong16** [comment]
#992

**Comment by RobinMM** [comment]
Oh just removed my post because i found issue was closed:

![pause-as-play](https://cloud.githubusercontent.com/assets/1236301/25353221/cd80f36e-292e-11e7-864a-a26b278879d6.jpg)
I am seeing this problem with a specific platform only, Rasplex. It happens sometimes a pause gets registered as playing. Result: Getting play times over 2000 minutes if someone leaves it on pause for 1 day. Quite annoying because of this issue the 'total duration' time gets corrupted. I need to purge these stats from time to time to keep stats clean and real.
