### ISSUE TITLE
Multiple Play Counts for Play/Pause Item

### ISSUE THREAD

**Issue by majora2007** [Tautulli/Tautulli#75]
I've observed that when a user starts/stops a movie multiple times during a playing session, PlexPy will actually count this as multiple plays, thus skewing data produced by the software. Is there a way to stitch the playing times together to determine if the item was watched or not?

Here is an image to showcase the issue: [link](http://imgur.com/uDxxBQJ)

**Comment by drzoidberg33** [comment]
I don't really know if you're logging this as an issue or a feature request but this is the expected behaviour, each time a new stream is started a new record is created.

Trying to aggregate plays is really tricky as there quite a few variables to consider like how long between plays do you count a play as a 'single play'? Or should a new stream played back at a different quality be logged separately or be aggregated, and if it should be aggregated how do we then know what the stream quality was?

**Comment by majora2007** [comment]
Good points, I didn't fully think about those cases. I'll have to do some extra thinking to see if there is a solution. By the way, great product and beautiful code. I'm learning a lot of stuff from reading through your code.

**Comment by drzoidberg33** [comment]
@majora2007 Hehe, I'm a serious Python noob I wouldn't call my code very good but glad you're learning something :laughing:
