### ISSUE TITLE
Under recently added "There was an error communicating with your Plex Server." on brand new install

### ISSUE THREAD

**Issue by keithah** [Tautulli/Tautulli#769]
**Version:**
1.4.6
**Branch:**
master
**Commit hash:**
d9474cdcc5e72ff311569a234e3abe7dec06d9a2
**Operating system:**
Ubuntu 14.04
**Python version:**
2.7.6
**What you did?**
Fresh install, setup plexpy
**What happened?**
Viewed the main page, got this error
**What you expected?**
To see recently added media like my old plexpy setup
**How can we reproduce your issue?**
Not sure, all I did was git clone, then run plexpy and add localhost and myplex to it.

**What are your (relevant) settings?**
no settings configured.
**Link to logs:**
2016-07-04 10:06:49 WARNING Unable to retrieve data for get_recently_added.
2016-07-04 10:06:49 WARNING PlexPy Pmsconnect :: Unable to parse XML for get_recently_added: 'NoneType' object has no attribute 'getElementsByTagName'.
2016-07-04 10:06:49 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=50. Status code 500

Full log: http://pastebin.com/QrwernX2

I searched and couldn't find why it's giving me 500 errors. Any ideas?

**Comment by keithah** [comment]
Everything is populating but 'recently added' on the main page.

**Comment by JonnyWong16** [comment]
Check your Plex IP and port in the settings. And verify/save the settings again.

**Comment by keithah** [comment]
Plex IP and port are good, verify works fine. I can see currently watching and I have history. Any other ideas?

**Comment by JonnyWong16** [comment]
Can you reach this page manually?

```
http://<plex_ip>:32400/library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=50X-Plex-Token=<your_plex_token>
```

**Comment by keithah** [comment]
I assume it's the PMS token in PlexPy under Plex.TV Account at the end of that url? If so, no, it gives 400 bad request.

**Comment by JonnyWong16** [comment]
You have some access issues on your server then.

**Comment by keithah** [comment]
my other plex server w/ a plexpy instance also does 400 bad request when going to the above url and doesn't have the recently added issue so I'm confused...

**Comment by JonnyWong16** [comment]
My bad, I forgot an `&` symbol.

```
http://<plex_ip>:32400/library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=<your_plex_token>
```

**Comment by JonnyWong16** [comment]
Still an issue?

**Comment by VikingSven82** [comment]
I have the same thing since the last Plex update, but I get it with Activity in PlexPy too, as well as recently added. Verifying the server in settings says it's fine. I tried changing the server IP from 127.0.0.1 to the LAN IP (which Plex says it's listening on) which didn't help.

I get these errors in PlexPy's log:
Unable to retrieve data for get_activity.
Unable to retrieve data for get_current_activity_header.
PlexPy Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'.
PlexPy Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'.
Failed to access uri endpoint /status/sessions. Status code 401
Failed to access uri endpoint /status/sessions. Status code 401

**Comment by JonnyWong16** [comment]
@VikingSven82 Status code 401 is authentication error. Go to the Settings > Plex.tv Account > Fetch a new token.

**Comment by VikingSven82** [comment]
Just done that, and restarted PlexPy and still get the same errors.

edit: nm, did it again and it worked this time!

**Comment by JonnyWong16** [comment]
Remove the "PlexPy" device from your server settings, then try fetching a token again.
