### ISSUE TITLE
Allow grouping of played items

### ISSUE THREAD

**Issue by vanstinator** [Tautulli/Tautulli#77]
Allow the grouping of played items so a user sees

10:00 User 1 Plays item 1

Instead of 

10:00 User 1 Plays item 1
10:10 User 1 Plays item 1
10:45 User 1 Plays item 1

There are some caveats. Imagine for instance

10:00 User 1 Plays item 1 at quality x
10:05 User 1 Stops item 1
10:10 User 1 Plays item 1 at quality z
10:15 User 1 Stops item 1
10:30 User 1 Plays item 1 at quality y
10:36 User 1 Stops item 1
10:40 User 1 Plays item 2
10:44 User 1 Stops item 2
11:00 User 1 Plays item 1 at quality y
11:30 User 1 Stops item 1
- How do we determine which items should be grouped? Does item 1 at 11:00 get grouped with the rest of item 1 before the user played item 2? How long do we wait before items are no longer groupable?
- The start and stop times vs duration. The start time of grouped item 1 is 10:00, the stop time is 11:30 (if we count in that last one). That's 1:30 of time passed but only 36 minutes of the item has been played. This should be correctly accounted for.
- The user has played the same item but at 3 different quality settings, should these items be grouped or not? If they are grouped we need to account for all three qualities somehow.
- Do we leave items separate if they're played from different devices? If User 1 started playing item 1 on device X, stops it and continues playing it on device Y that cannot be grouped.
- Do we write a new database table for this (like with PlexWatch) or do we query on the fly (not a simple task as there are many queries).
  Not impossible but it definitely is quite a challenge. PlexWatch trips up with a few of the above.

**Comment by drzoidberg33** [comment]
Does this apply for all places where play counts get registered (e.g. graphs) or only in the tables?

**Comment by vanstinator** [comment]
Graphs too.

"As a user I want the option to display "Plays" as a holistic viewing of a movie. If I stop and start a movie within a specified time frame I would like the data to show that I watched the movie one time, not 2-4 times depending on how many times I stop the film."

If that's our use case I think all data should be displayed with the assumption plays are grouped or not. In that case a new database table definitely makes the most sense so that we can use the same queries and just hit a table, which table being defined by a user option for grouping.

**Comment by kylerw** [comment]
+1

**Comment by ooii** [comment]
What about implementing it the same way as plexwatch (https://github.com/ljunkie/plexWatch#advanced-options---configpl)?

**Comment by drzoidberg33** [comment]
@ooii There is definitely a lot of good reading in the PlexWatch code but the programs are quite different. PlexWatch also suffers from some of the pitfalls mentioned in the first post.

**Comment by ooii** [comment]
I trust you. It was only my acts help attempt :)

**Comment by Chrisophogus** [comment]
This would be a really useful enhancement.
Personally, I'd go for the simplest version. Until someone has watched more than a certain %'age it should always be counted as a single watch.
Of course, there's numerous other caveats that will pop up, if someone is only 2 minutes in, pauses and then starts from the beginning etc. But as a first instance I think working by %'age viewed is a good start.

**Comment by skotsjedal** [comment]
This would help a bit, I get many double counts for for example, I watch 20% in the browser, then cast the rest to chromecast, counts as two. Or plex on playstation crashes halfway through a movie, resuming makes it count twice.

**Comment by JonnyWong16** [comment]
Here is my idea:
- Group only if **successive plays** are the same item on the same platform. Time in between stopping and re-starting an item is irrelevant.
- Display the grouped start/stop time with total played duration (and total paused time). Display the most recent quality (the stream info when clicking the platform).
- Use datatable [Child Row](https://www.datatables.net/examples/api/row_details.html) API to expand the rows to show the individual history. This would address the multiple qualities problem.
- Off the top of my head, I think there are only 12 queries that need major changes (one history table, and eleven graphs). The others like home stats, should only be minor changes. This is doable, since all the graph queries are similar.

Example:

![Grouped History Example](https://www.dropbox.com/s/xl95f7weew7svjb/shot_150914_005425.png?dl=1)
- Optional: Take it one step further and group even if the platform is different. Display the most recent platform, and the expanded rows would show the individual platform.

**Comment by drzoidberg33** [comment]
I've commented this on https://github.com/drzoidberg33/plexpy/pull/190:

A new db table is the only solution I think that would make this viable.

I'm guessing we would only need one new table session_history_aggregated which is a clone of session_history and just contains two extra columns children_ids which contains a comma separated list of id keys which form part of the group and reference_id which is the id of the first item written (to make referencing the other tables easier).

The logic to group should then be done in a python function on a history write action, after the normal session_history write is completed it should then do the check for similar items to group and append the id from the session_history into the children_ids field if a suitable item is found otherwise write a new record to session_history_aggregated.

This logic is basically what hasn't be completely fleshed out yet. One thing that works for one user may not work for another so it should probably err more on grouping a bit conservatively. Basically something like:

if rating_key = rating_key and user_id = user_id and view_offset > view_offset then group

Calling grouped history items is then as simple as changing the reference to the table name and id for the joins.

We would also need to create a script that would automatically generate this table from the existing data when a user upgrades.

**Comment by JamminR** [comment]
Please work on this in top 5 feature requests. (Bugs always come first of course, imo)
Additionally, I'm more than willing to test it for you. I've got household members that go from Iphone to Ipad to Roku within a 1-2 hour period. I grow weary of the many history lines, and stats being thrown off when using 'count' instead of duration. Even in duration mode, some user stats are still showing incorrectly.
I still keep Plexwatch going in the background to be able to import should something go wrong when you tinker in Plexpy.

**Comment by epheterson** [comment]
No movement in a year and a half, could we pick this up again? 

I came here to file this and am glad to see it's a common idea that's been well thought out. Specifically when it comes to show counts, counting a single show viewed in multiple parts as multiple entire viewings of that show artificially inflates the data, decreasing its usefulness.

**Comment by epheterson** [comment]
Oh perhaps this issue is still open after it's been fixed, I found this feature:

Group Table and Watch Statistics History
Group successive play history by the same user as a single entry in the tables and watch statistics.
