### ISSUE TITLE
History Tab no longer updates

### ISSUE THREAD

**Issue by BSOD2600** [Tautulli/Tautulli#802]
**Version:**
1.4.8

**Branch:**
master

**Commit hash:**
2150961d2742afc24d5982fe3d0ddee141f89a26

**Operating system:**
Windows 7 x64

**Python version:**
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**What you did?**
Nothing that I know of.  Just stopped updating on 2016-06-20

**How can we reproduce your issue?**
Not sure. Users watching content in Plex does show up in PlexPy real time, so at least that communication works.  

**Link to logs:**
Following debug error is occurring frequently.  otherwise nothing appears abnormal:
    PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'

**Comment by carsso** [comment]
I had the same problem since 2016-07-30 (same version, 2150961).
I used plexpy since months and I never had that kind of problem before.
In the logs, the only thing I can see is there is no more "DEBUG   :: Thread-1 : PlexPy ActivityProcessor ::" and "DEBUG   :: Thread-1 : PlexPy ActivityHandler ::" lines from 2016-07-30.

Full log: https://plik.root.gg/file/IB76Jlcl0LHntIG3/Mqs9lrd0tgb856em/plexpy_logs.log

The only suspicious thing is 

```
2016-07-30 18:35:28 - ERROR   :: Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/plexpy/plexpy/web_socket.py", line 101, in run
    logger.info(u"PlexPy WebSocket :: %s." % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
```

Hopefully I also have plexWatch. So, I checked if everything was well configured, stopped/restarted plexpy, imported plexWatch db (to get the history between 2016-07-30 and now) and everything is now back up and running (and nothing has been lost).
And as you can see, at the bottom of the log, after the reboot and the import, there are some "DEBUG   :: Thread-1 : PlexPy ActivityHandler :: " lines, yaaaaay !

I hope it would help.

**Comment by JonnyWong16** [comment]
Try going to 

```
http://localhost:8181/delete_temp_sessions
```

This will flush out any sessions that got stuck in the database.

**Comment by Arcanemagus** [comment]
Is there any reason that utility function shouldn't be ran on starting PlexPy?

**Comment by JonnyWong16** [comment]
@Arcanemagus If you restart PlexPy while there is a stream, it needs to continue logging after starting back up.

**Comment by BSOD2600** [comment]
temp sessions deleted.  Played a show in plex web for 2 min and then stopped.  History does show for the user.   Now I wait for other users to validate ;) 

2016-08-05 07:34:57 DEBUG   PlexPy Monitor :: Removing sessionKey 18 ratingKey 379604 from session queue
2016-08-05 07:34:57 DEBUG   PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 379604
2016-08-05 07:34:57 DEBUG   PlexPy Monitor :: Session 18 has stopped.
2016-08-05 07:32:57 DEBUG   PlexPy Monitor :: Session 18 has started.
2016-08-05 07:32:10 DEBUG   PlexPy Database :: Clearing temporary sessions from database.
2016-08-05 07:31:57 DEBUG   PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'

**Comment by carsso** [comment]
For me everything is working since my stop/restart. I've also flushed the sessions as suggested and it still works ;)

**Comment by BSOD2600** [comment]
History tab still working ever since the temp session clear.

Maybe add this check or run it on every upgrade so it doesnt happen again?

**Comment by mpkogli** [comment]
@JonnyWong16 the `http://localhost:8181/delete_temp_sessions` fix worked for me, thanks!

Is there not a way to do this within the UI?

**Comment by JonnyWong16** [comment]
@mpkogli Settings > Extra Settings > Flush Temporary Sessions
