### ISSUE TITLE
[Task] Implement automated database backups

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli#89]
There should be an automated process running periodically which keeps a few days worth of database backups.

**Comment by Hellowlol** [comment]
+1

**Comment by Snille** [comment]
+1 :)

**Comment by Hellowlol** [comment]
A backup function is added in the api pr. It is not a automatic backup tho.

**Comment by JonnyWong16** [comment]
It's easy to add the backup to the scheduler after merging #377.

**Comment by JonnyWong16** [comment]
Added in v1.3.7.

Backups the database every 6 hours, and keeps last 5 backups. Let me know if those numbers should be increased/changed.

**Comment by jelliuk** [comment]
@JonnyWong16 - Rather than create a new issue I thought I would be best comment on the feature implementation.  As an enhancement, would it be possible to have a configurable variable where we could propose an alternative directory which the backups are written to?  My main thinking is that if the existing DB and backups are held within the same disk, if that disk fails/corrupts, unless I've manually moved the backup previously and of course recently, I'll have lost the ability to restore assuming no resilience.

I guess I could symlink but I always feel it's neater to have this managed via application that some configuration on the host which can be forgotten.

**Comment by Hellowlol** [comment]
The backup was added since there has been some cases where the db has been corrupted. As bandaid you can copy the datafolder in a crontab.

**Comment by JonnyWong16** [comment]
You can change the backup folder in the `config.ini` file.

**Comment by Hellowlol** [comment]
I think he meant that he wanted a second backup in case the drive that datafolder is on is fried. I might be wrong :P

**Comment by jelliuk** [comment]
@JonnyWong16 @Hellowlol 

Hi Both, apologies for not being clear in the requirement.  It's actually more the separation of the in-use database and the backup database from the same underlying hardware such that if a drive is lost and both (i.e. production and backup) are stored there, the whole world isn't lost.  All eggs in one basket phrase comes to mind.

I'll take a look at Jonny's suggestion as that's what I'm looking for.  I didn't realise this was available via the ini file.  It might be something worth exploring as a configurable option via the GUI at a later stage, though appreciate it might be niche.

**Comment by JonnyWong16** [comment]
Make sure PlexPy is shut down when making changes to the `config.ini` file. You can verify the change sticks by checking the "Backup folder" under the Help & Info page in the settings. Then if you go to

```
http://localhost:8181/backup_db
```

It should trigger a manual back up of the db to the new folder to make sure the scheduled backup will send the backups to the new folder.

**Comment by jelliuk** [comment]
Not sure if I've got an issue with how I'm trying to do this but I can't get the configuration to stick.  I've gone into PlexPy Settings -> Shutdown, watched Python initiate the shutdown, python cmd line window closes, PlexPy URL stops responding.  

Initial setting config.ini:
`backup_dir = C:\Users\Admin\Documents\PlexPy\backups`

Change made to config.ini (definitely saved it post change):
`backup_dir = H:\Backup\PlexPy\backups`

On loading PlexPy up via the Python executable, the setting appears to revert to the initial setting described above.  I'm not sure if the config appears to overwrite with the default setting on startup as I can see in the [PlexPy Log](https://gist.github.com/jelliuk/ba62997b4a545e6b3f5e) that there are two entries regarding writing to the configuration file on startup:

```
2016-03-02 16:29:58 INFO    Writing configuration to file

2016-03-02 16:29:59 INFO    Writing configuration to file
```

OS - Windows 10
Python -    2.7.10 
Branch - Master (Version - 1.3.9)

This happens regardless of creating the directory or not.  H:\ is a USB Disk, not sure if this alters things at all.

Happy to carve this out as a separate issue rather than fill this up (not sure if I hijacked this thread now) or close it as it's kind of trying to do something not officially exposed via the GUI.

**Comment by JonnyWong16** [comment]
Ah, I think it resets back to the default folder since there isn't a feature to change the backup folder yet. (https://github.com/drzoidberg33/plexpy/blob/master/plexpy/__init__.py#L124)

Open a new feature request for changing the backup folder so this request doesn't get lost.
