### ISSUE TITLE
[Request] A Map graph

### ISSUE THREAD

**Issue by kylerw** [Tautulli/Tautulli#94]
I think it might be cool to see where watches are coming from. With the IP logging we know an approximate city/state - maybe a heatmap or something else to help visualize this?

**Comment by drzoidberg33** [comment]
I had the same idea. It would require me to package quite a large IP geolocation database with PlexPy though.

Also not sure how many people would find this useful.

Cool idea still.

**Comment by kylerw** [comment]
The ip-api.com results return a lat/long that I assume could be dropped fairly easily into something like https://code.google.com/p/pygmaps/, https://plot.ly or http://matplotlib.org/basemap/

**Comment by drzoidberg33** [comment]
The only problem is those queries are often slow, time out and you are only limited to a certain number of api calls per hour/day. Trying to call up data for 500 IP addresses for instance will be impossible.

I've looked at integrating with the Maxmind database in the past, but it's quite a task to get the data needed without having databases in excess of 100MBs.

**Comment by kylerw** [comment]
I've used http://www.telize.com/ in the past for small batch requests and it seems to run pretty quick. Not sure how it would fair with hundreds of requests.

If the lat/long was recorded with each 'play', would that allow for minimal additional DB resources?

**Comment by Arcanemagus** [comment]
@kylerw telize doesn't post this, but they start inserting a 10s delay if you do more than some ridiculously small number of queries. It was small enough that manually testing the query timing I was hitting issues with it.

I actually didn't even include it in my data because it was unusable for anything automated without some crazy long queueing.

If either of you were interested here is the data I gathered while looking into this: https://docs.google.com/spreadsheets/d/11Nad_EVA38R5n1Af4bXg3DH5xoyjpRk-Ha0YUGH856U/edit?usp=sharing
(It doesn't show it on the spreadsheet but it didn't matter what report format you requested (JSON, XML, text), or whether it was IPv4 or IPv6 if the service supported it)

**Comment by drzoidberg33** [comment]
Thanks @Arcanemagus that's quite cool that you've done some testing on these services.

At the end of the day though there isn't a free service that provides something that would do this reliably for anyone doing a large number of requests. 

Do any of these services do batch requests? Because even if we got a free service that handled a large number of requests the request/response time would make it unusable if we can only query one IP at a time.

**Comment by Arcanemagus** [comment]
In plexWatchWeb it currently just queries every time you load the history.... which is ridiculous. Haven't worked on any persistence yet on the results so it's a pain. Unfortunately as far as I saw none of them support batch queries unfortunately.

You have the major advantage of a persistent service here so you could have a "IP cache/query" service set up that queues up requests and caches responses.

**Comment by vladc** [comment]
@drzoidberg33 please contact me at contact@ip-api.com - we can probably help with batch requests.

**Comment by BehrozKarimi** [comment]
+1

**Comment by neebski** [comment]
+1

**Comment by mattyteds** [comment]
The geolocation data for IP address isn't very accurate. The map created wouldn't really be useful. [http://whatismyipaddress.com/geolocation-accuracy](http://whatismyipaddress.com/geolocation-accuracy)

**Comment by DejaVu** [comment]
How accurate would it need to be? 
Once PlexPy has an idea where the user is, can it not just check once every 5 or 10 plays instead of everytime? Then just go by the number of plays to how much Hotness for that area? 
The world map is a pretty big place... or indeed go by the IP Addresses already logged and number of plays.
I think the stats are there really, just need to implement it. 
It only has to be approximate anyway, unless you want a zoom in feature, which then makes it more complicated. 

I just think it'll be a nice thing to look at to get an idea where your Plex Server is being used. 

![world map](https://cloud.githubusercontent.com/assets/481679/19760731/e5551ad8-9c2a-11e6-8f78-9c8446e1182a.png)

**Comment by PilaScat** [comment]
no news about this?
